package com.invasion.nexus.wave;

import java.util.ArrayList;
import java.util.List;

import com.invasion.nexus.wave.pool.Select;

public interface Waves {
    List<Wave.Builder> WAVES = new ArrayList<>();
    Select.PoolBuilder<EntityPattern, Float> WAVE_TWO_BASE_POOL = Select.<EntityPattern>random()
            .entry(EntityPatterns.ZOMBIE_T1_ANY, 3F)
            .entry(EntityPatterns.SPIDER_T1_ANY, 1F)
            .entry(EntityPatterns.SKELETON_T1_ANY, 0.7F)
            .entry(EntityPatterns.ZOMBIE_PIGMAN_T1_ANY, 0.5F)
            .entry(EntityPatterns.CREEPER_T1_BASIC, 0.038F);
    Select.PoolBuilder<EntityPattern, Float> WAVE_THREE_BASE_POOL = Select.<EntityPattern>random()
            .entry(EntityPatterns.ZOMBIE_T1_ANY, 3F)
            .entry(EntityPatterns.SPIDER_T1_ANY, 1F)
            .entry(EntityPatterns.SKELETON_T1_ANY, 0.7F)
            .entry(EntityPatterns.CREEPER_T1_BASIC, 0.04F);
    Select.PoolBuilder<EntityPattern, Float> WAVE_FOUR_BASE_POOL = Select.<EntityPattern>random()
            .entry(EntityPatterns.ZOMBIE_T1_ANY, 3F)
            .entry(EntityPatterns.SPIDER_T1_ANY, 1F)
            .entry(EntityPatterns.SKELETON_T1_ANY, 0.7F)
            .entry(EntityPatterns.CREEPER_T1_BASIC, 0.058F);
    Select.PoolBuilder<EntityPattern, Float> WAVE_TEN_BASE_POOL = Select.<EntityPattern>random()
            .entry(EntityPatterns.ZOMBIE_T1_ANY, 1.5F)
            .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 2.2F)
            .entry(EntityPatterns.ZOMBIE_PIGMAN_T1_ANY, 0.7F)
            .entry(EntityPatterns.SPIDER_T1_ANY, 0.7F)
            .entry(EntityPatterns.SKELETON_T1_ANY, 0.7F)
            .entry(EntityPatterns.CREEPER_T1_BASIC, 0.084F);
    Select.PoolBuilder<EntityPattern, Float> WAVE_FIVE_BASE_POOL = Select.<EntityPattern>random()
            .entry(EntityPatterns.ZOMBIE_T1_ANY, 3F)
            .entry(EntityPatterns.SPIDER_T1_ANY, 1F)
            .entry(EntityPatterns.SKELETON_T1_ANY, 0.7F)
            .entry(EntityPatterns.CREEPER_T1_BASIC, 0.054F);
    Select.PoolBuilder<EntityPattern, Float> WAVE_SIX_BASE_POOL = Select.<EntityPattern>random()
            .entry(EntityPatterns.ZOMBIE_T1_ANY, 2F)
            .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 1F)
            .entry(EntityPatterns.SPIDER_T1_ANY, 0.7F)
            .entry(EntityPatterns.SKELETON_T1_ANY, 0.7F)
            .entry(EntityPatterns.CREEPER_T1_BASIC, 0.064F);
    Select.PoolBuilder<EntityPattern, Float> WAVE_EIGHT_BASE_POOL = Select.<EntityPattern>random()
            .entry(EntityPatterns.ZOMBIE_T1_ANY, 2F)
            .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 1.5F)
            .entry(EntityPatterns.SPIDER_T1_ANY, 0.7F)
            .entry(EntityPatterns.SKELETON_T1_ANY, 0.7F)
            .entry(EntityPatterns.CREEPER_T1_BASIC, 0.064F);
    Wave.Builder WAVE_1 = register(Wave.builder(110000, 15000)
            .entry(WaveEntry.random()
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 3F)
                    .entry(EntityPatterns.SPIDER_T1_ANY, 1F)
                    .end(90000).amount(8).granularity(2000))
            .entry(WaveEntry.random()
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1F)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 2F)
                    .begin(70000).end(73000).amount(3).granularity(500).angle(25).minSpawns(3)));
    Wave.Builder WAVE_2 = register(Wave.builder(120000, 15000)
            .entry(WaveEntry.builder(WAVE_TWO_BASE_POOL).end(50000).amount(5).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.builder(WAVE_TWO_BASE_POOL).begin(50000).end(100000).amount(5).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.random().entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1F).begin(20000).end(23000).amount(1).granularity(500))
            .entry(WaveEntry.random().entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1F).begin(20000).end(23000).amount(1).granularity(500))
            .entry(WaveEntry.random().entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1F).entry(EntityPatterns.ZOMBIE_T1_ANY, 2F).begin(65000).end(68000).amount(3).granularity(500).angle(25).minSpawns(2)));
    Wave.Builder WAVE_3 = register(Wave.builder(120000, 18000)
            .entry(WaveEntry.builder(WAVE_THREE_BASE_POOL).end(30000).amount(6).granularity(2000).angle(45).minSpawns(3))
            .entry(WaveEntry.builder(WAVE_THREE_BASE_POOL).begin(80000).end(100000).amount(5).granularity(2000).angle(45).minSpawns(3))
            .entry(WaveEntry.random().entry(EntityPatterns.SPIDER_T2_ANY, 1F).begin(10000).end(12000).amount(1).granularity(500))
            .entry(WaveEntry.finite().entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_T2_PLAIN, 1)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 1)
                    .entry(EntityPatterns.SPIDER_T1_ANY, 1)
                    .entry(EntityPatterns.CREEPER_T1_BASIC, 1).begin(50000).end(55000).amount(5).granularity(500).angle(25).minSpawns(6).alert("invmod.message.wave.groupsmall", 0)));
    Wave.Builder WAVE_4 = register(Wave.builder(120000, 18000)
            .entry(WaveEntry.builder(WAVE_FOUR_BASE_POOL).end(50000).amount(6).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.builder(WAVE_FOUR_BASE_POOL).begin(50000).end(100000).amount(6).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1).end(90000).amount(3).granularity(500))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 1)
                    .entry(EntityPatterns.ZOMBIE_PIGMAN_T2_ANY, 1).begin(70000).end(75000).amount(2).granularity(500).angle(25).minSpawns(2)));
    Wave.Builder WAVE_5 = register(Wave.builder(130000, 80000)
            .entry(WaveEntry.builder(WAVE_FIVE_BASE_POOL).end(40000).amount(6).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.builder(WAVE_FIVE_BASE_POOL).begin(40000).end(80000).amount(6).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 3)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 1)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 1)
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .entry(EntityPatterns.THROWER_T1, 1).begin(115000).end(118000).amount(8).granularity(500).angle(35).minSpawns(5).alert("invmod.message.wave.grouplarge", 0))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 3)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 1)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 1)
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .entry(EntityPatterns.SPIDER_T1_ANY, 1).begin(135000).end(165000).amount(7).granularity(500)));
    Wave.Builder WAVE_6 = register(Wave.builder(110000, 25000)
            .entry(WaveEntry.builder(WAVE_SIX_BASE_POOL).end(50000).amount(7).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.builder(WAVE_SIX_BASE_POOL).begin(50000).end(100000).amount(6).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .end(90000).amount(2).granularity(500))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 2)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_PIGMAN_T1_ANY, 1).begin(70000).end(75000).amount(4).granularity(500).angle(25).minSpawns(2)));
    Wave.Builder WAVE_7 = register(Wave.builder(120000, 36000)
            .entry(WaveEntry.random()
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 2F)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 1F)
                    .entry(EntityPatterns.SPIDER_T1_ANY, 0.7F)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 0.7F)
                    .entry(EntityPatterns.CREEPER_T1_BASIC, 0.064F).end(30000).amount(7).granularity(2000).angle(45).minSpawns(5))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .entry(EntityPatterns.THROWER_T1, 1).end(60000).amount(3).granularity(500))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 2)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_PIGMAN_T1_ANY, 1)
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .begin(65000).end(67000).amount(5).granularity(500).angle(45).minSpawns(2))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_PIGMAN_T1_ANY, 3)
                    .begin(95000).end(97000).amount(4).granularity(500).angle(45).minSpawns(2)));
    Wave.Builder WAVE_8 = register(Wave.builder(110000, 30000)
            .entry(WaveEntry.builder(WAVE_EIGHT_BASE_POOL).end(35000).amount(7).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.builder(WAVE_EIGHT_BASE_POOL).begin(80000).end(110000).amount(4).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1).end(90000).amount(2).granularity(500))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 3)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 2)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 1)
                    .entry(EntityPatterns.CREEPER_T1_BASIC, 1).begin(60000).end(63000).amount(8).granularity(500).angle(25).minSpawns(2).alert("invmod.message.wave.group", 0)));
    Wave.Builder WAVE_9 = register(Wave.builder(120000, 35000)
            .entry(WaveEntry.random()
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 2F)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 2F)
                    .entry(EntityPatterns.SPIDER_T1_ANY, 0.7F)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 0.7F)
                    .entry(EntityPatterns.CREEPER_T1_BASIC, 0.074F).end(30000).amount(7).granularity(2000).angle(45).minSpawns(5))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1).end(90000).amount(3).granularity(500))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_PIGMAN_T1_ANY, 3)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 1)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 1)
                    .entry(EntityPatterns.ZOMBIE_T3_ANY, 1).begin(65000).end(67000).amount(6).granularity(500).angle(25).minSpawns(3))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 2)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 3)
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1).begin(95000).end(97000).amount(6).granularity(500).angle(45).minSpawns(2)));
    Wave.Builder WAVE_10 = register(Wave.builder(172000, 60000)
            .entry(WaveEntry.builder(WAVE_TEN_BASE_POOL).end(40000).amount(9).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.builder(WAVE_TEN_BASE_POOL).begin(40000).end(80000).amount(7).granularity(2000).angle(110).minSpawns(5))
            .entry(WaveEntry.random()
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1F)
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1F).end(80000).amount(3).granularity(500))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 2)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 2)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 2)
                    .entry(EntityPatterns.ZOMBIE_PIGMAN_T1_ANY, 3)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 1)
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .entry(EntityPatterns.THROWER_T1, 1)
                    .begin(125000).end(128000).amount(12).granularity(500).angle(35).minSpawns(5).alert("invmod.message.wave.grouplarge", 0))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 2)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 2)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 1)
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .entry(EntityPatterns.SPIDER_T1_ANY, 2)
                    .begin(152000).end(170000).amount(7).granularity(500)));
    Wave.Builder WAVE_11 = register(Wave.builder(120000, 35000)
            .entry(WaveEntry.random()
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 1.5F)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 2.2F)
                    .entry(EntityPatterns.ZOMBIE_T3_ANY, 0.185F)
                    .entry(EntityPatterns.ZOMBIE_PIGMAN_T1_ANY, 0.8F)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 0.7F)
                    .entry(EntityPatterns.THROWER_T1, 0.1F)
                    .entry(EntityPatterns.CREEPER_T1_BASIC, 0.064F)
                    .end(30000).amount(7).granularity(2000).angle(45).minSpawns(5))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1)
                    .end(90000).amount(3).granularity(500))
            .entry(WaveEntry.random()
                    .entry(EntityPatterns.PIGMAN_ENGINEER_T1_ANY, 1F)
                    .entry(EntityPatterns.ZOMBIE_PIGMAN_T1_ANY, 2F)
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 3F)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 1F)
                    .entry(EntityPatterns.SKELETON_T1_ANY, 1F)
                    .entry(EntityPatterns.THROWER_T1, 0.8F)
                    .entry(EntityPatterns.CREEPER_T1_BASIC, 0.8F).begin(65000).end(67000).amount(7).granularity(500).angle(25).minSpawns(3))
            .entry(WaveEntry.finite()
                    .entry(EntityPatterns.ZOMBIE_T2_ANY_BASIC, 2)
                    .entry(EntityPatterns.ZOMBIE_T1_ANY, 3)
                    .entry(EntityPatterns.SPIDER_T2_ANY, 1)
                    .begin(95000).end(97000).amount(6).granularity(500).angle(45).minSpawns(2)));

    static Wave.Builder register(Wave.Builder builder) {
        WAVES.add(builder);
        return builder;
    }
}
